/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.OracleTypes;
import static reto.Reto.ap;
import static reto.Reto.model;

/**
 *
 * @author m
 */
public class Gestion extends javax.swing.JFrame {

public static GestionCentros gc=new GestionCentros();
public static GestionTrabajadores gt=new GestionTrabajadores();

public static DefaultTableModel model= (DefaultTableModel) gc.getjTable1().getModel();
public static DefaultTableModel model2= (DefaultTableModel) gt.getjTable1().getModel();
/**
 * Creates new form Gestionar
 */
public Gestion() {
	initComponents();
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jButton1 = new javax.swing.JButton();
                jButton2 = new javax.swing.JButton();
                jButton3 = new javax.swing.JButton();
                jButton4 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("GESTION DE LA EMPRESA");

                jButton1.setText("CENTROS");
                jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jButton1MouseClicked(evt);
                        }
                });
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton1ActionPerformed(evt);
                        }
                });

                jButton2.setText("TRABAJADORES");
                jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                jButton2MouseClicked(evt);
                        }
                });

                jButton3.setText("VEHICULOS");

                jButton4.setText("CONDUCEN");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
                model.setRowCount(0);
		gc.setVisible(true);
	try {
		verCentros();
	} catch (ClassNotFoundException | SQLException ex) {
		Logger.getLogger(Gestion.class.getName()).log(Level.SEVERE, null, ex);
	}
		
		
        }//GEN-LAST:event_jButton1MouseClicked

        private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
                     model2.setRowCount(0);
		gt.setVisible(true);
	try {
		verTrabajadores();
	} catch (ClassNotFoundException | SQLException ex) {
		Logger.getLogger(Gestion.class.getName()).log(Level.SEVERE, null, ex);
	}
        }//GEN-LAST:event_jButton2MouseClicked

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				javax.swing.UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	} catch (ClassNotFoundException ex) {
		java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
		java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
		java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
		java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	public void run() {
		new Gestion().setVisible(true);
	}
	});
}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JButton jButton4;
        // End of variables declaration//GEN-END:variables
public static void actualizarCentros(){
                 model.setRowCount(0);
                    
	     //if(model.getRowCount()>0)
		//for (int i=0;i<model.getRowCount();i+=1){
		//model.removeRow(i);}
	            

}
public static void verCentros() throws ClassNotFoundException, SQLException{	
	
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "reto", "dragon13");
	
	String sql="{call seleccionarCentros (?)}";
        
	CallableStatement llamada = conexion.prepareCall(sql);
	
	llamada.registerOutParameter("c", OracleTypes.CURSOR);
	
	llamada.executeUpdate();
	
	ResultSet rs = (ResultSet) llamada.getObject("c");
	
	
	while (rs.next()) {
	
	BigDecimal resultado1 = rs.getBigDecimal(1);
	String resultado2 = rs.getString(2);
	String resultado3 = rs.getString(3);
	BigDecimal resultado4 = rs.getBigDecimal(4);
	String resultado5 = rs.getString(5);
	BigDecimal resultado6 = rs.getBigDecimal(6);
	String resultado7 = rs.getString(7);
	BigDecimal resultado8 = rs.getBigDecimal(8);
	
        
	model.addRow(new Object[]{resultado1,resultado2,resultado3,resultado4,resultado5,resultado6,resultado7,resultado8 });
	
	
	}
	
	rs.close();
	llamada.close();
	conexion.close();
}
public static void verTrabajadores() throws ClassNotFoundException, SQLException{	
	
	Class.forName("oracle.jdbc.driver.OracleDriver");
	Connection conexion = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe", "reto", "dragon13");
	
	String sql="{call seleccionarTrabajadores (?)}";
        
	CallableStatement llamada = conexion.prepareCall(sql);
	
	llamada.registerOutParameter("c", OracleTypes.CURSOR);
	
	llamada.executeUpdate();
	
	ResultSet rs = (ResultSet) llamada.getObject("c");
	
	
	while (rs.next()) {
	
	BigDecimal resultado1 = rs.getBigDecimal(1);
	String resultado2 = rs.getString(2);
	String resultado3 = rs.getString(3);
	String resultado4 = rs.getString(4);
	String resultado5 = rs.getString(5);
	String resultado6 = rs.getString(6);
	String resultado7 = rs.getString(7);
	BigDecimal resultado8 = rs.getBigDecimal(8);
	BigDecimal resultado9 = rs.getBigDecimal(9);
	String resultado10 = rs.getString(10);
	String resultado11 = rs.getString(11);
	BigDecimal resultado12 = rs.getBigDecimal(12);
	String resultado13 = rs.getString(13);
	BigDecimal resultado14 = rs.getBigDecimal(14);
	BigDecimal resultado15 = rs.getBigDecimal(15);
	BigDecimal resultado16 = rs.getBigDecimal(16);
	Date resultado17=rs.getDate(17);
	BigDecimal resultado18 = rs.getBigDecimal(18);
	
        
	model2.addRow(new Object[]{resultado1,resultado2,resultado3,resultado4,resultado5,resultado6,resultado7,
		resultado8, resultado9,resultado10,resultado11,resultado12,resultado13,resultado14,resultado15,
	        resultado16,resultado17,resultado18});
	
	
	}
	
	rs.close();
	llamada.close();
	conexion.close();
}

}
