DROP
  TABLE AVISOS CASCADE CONSTRAINTS ;

DROP
  TABLE CENTROS CASCADE CONSTRAINTS ;

DROP
  TABLE PARTES CASCADE CONSTRAINTS ;

DROP
  TABLE TRABAJADORES CASCADE CONSTRAINTS ;

DROP
  TABLE USUARIOS CASCADE CONSTRAINTS ;

DROP
  TABLE VEHICULOS CASCADE CONSTRAINTS ;

DROP
  TABLE VIAJES CASCADE CONSTRAINTS ;

CREATE
  TABLE AVISOS
  (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    aviso           VARCHAR2 (1000) NOT NULL ,
    TRABAJADORES_ID NUMBER (7) ,
    FECHA_ID        DATE
  ) ;
ALTER TABLE AVISOS ADD CONSTRAINT AVISOS_PK PRIMARY KEY ( ID ) ;


CREATE
  TABLE CENTROS
  (
    ID           NUMBER GENERATED ALWAYS AS IDENTITY,
    nombre       VARCHAR2 (50) NOT NULL ,
    calle        VARCHAR2 (200) NOT NULL ,
    numero       NUMBER (7) NOT NULL ,
    ciudad       VARCHAR2 (50) NOT NULL ,
    codigoPostal NUMBER (7) NOT NULL ,
    provincia    VARCHAR2 (50) NOT NULL ,
    telefono     NUMBER (15) NOT NULL
  ) ;
ALTER TABLE CENTROS ADD CONSTRAINT CENTROS_PK PRIMARY KEY ( ID ) ;


CREATE
  TABLE PARTES
  (
    fecha             DATE NOT NULL ,
    kmInicial         NUMBER (7) DEFAULT 0 NOT NULL ,
    kmFinal           NUMBER (7) DEFAULT 0 NOT NULL ,
    gastosPeaje       NUMBER (7,2) DEFAULT 0 ,
    gastosDietas      NUMBER (7,2) DEFAULT 0 ,
    gastosCombustible NUMBER (7,2) DEFAULT 0 ,
    otrosGastos       NUMBER (7,2) DEFAULT 0 ,
    incidencias       VARCHAR2 (1000) ,
    estado            VARCHAR2 (7) DEFAULT 'ABIERTO' ,
    validado          VARCHAR2 (2) DEFAULT 'NO' ,
    TRABAJADORES_ID   NUMBER (7) NOT NULL
  ) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_STD_CHK CHECK ( estado IN ('ABIERTO',
'CERRADO')) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_VLD_CHK CHECK ( validado IN ('NO', 'SI'))
;
ALTER TABLE PARTES ADD CONSTRAINT PRT_KMF_CHK CHECK (kmFinal           > kmInicial) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_KMI_CHK CHECK (kmInicial         < kmFinal) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_KMII_CHK CHECK (kmInicial       >=0) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_GSP_CHK CHECK (gastosPeaje      >=0) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_GSC_CHK CHECK (gastosCombustible>=0) ;
ALTER TABLE PARTES ADD CONSTRAINT PRT_OTG_CHK CHECK (otrosGastos      >=0) ;
ALTER TABLE PARTES ADD CONSTRAINT PARTES_PK PRIMARY KEY ( TRABAJADORES_ID,
fecha ) ;


CREATE
  TABLE TRABAJADORES
  (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY,
    dni             VARCHAR2 (9) NOT NULL ,
    nombre          VARCHAR2 (50) NOT NULL ,
    primerApellido  VARCHAR2 (20) NOT NULL ,
    segundoApellido VARCHAR2 (20) ,
    categoria       VARCHAR2 (25) NOT NULL ,
    calle           VARCHAR2 (200) NOT NULL ,
    numero          NUMBER (4) NOT NULL ,
    piso            NUMBER (2) ,
    mano            VARCHAR2 (20) ,
    ciudad          VARCHAR2 (50) NOT NULL ,
    codigoPostal    NUMBER (5) NOT NULL ,
    provincia       VARCHAR2 (50) NOT NULL ,
    movilEmpresa    NUMBER (15) NOT NULL ,
    movilPersonal   NUMBER (15) ,
    salario         NUMBER (9,2) ,
    fechaNacimiento DATE ,
    CENTROS_ID      NUMBER (7) NOT NULL
  ) ;
ALTER TABLE TRABAJADORES ADD CONSTRAINT TRABAJADORES_PK PRIMARY KEY ( ID ) ;


CREATE
  TABLE USUARIOS
  (
    usuario         VARCHAR2 (25) NOT NULL ,
    password        VARCHAR2 (30) NOT NULL ,
    TRABAJADORES_ID NUMBER (7) NOT NULL
  ) ;
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_PK PRIMARY KEY ( usuario ) ;


CREATE
  TABLE VEHICULOS
  (
    ID        NUMBER GENERATED ALWAYS AS IDENTITY,
    marca     VARCHAR2 (50) NOT NULL ,
    modelo    VARCHAR2 (50) NOT NULL ,
    matricula VARCHAR2 (15) NOT NULL ,
    fecha     NUMBER (7)
  ) ;
ALTER TABLE VEHICULOS ADD CONSTRAINT VEHICULOS_PK PRIMARY KEY ( ID ) ;


CREATE
  TABLE VIAJES
  (
    horaInicial     NUMBER (4,2) DEFAULT 0 NOT NULL ,
    horaFinal       NUMBER (4,2) DEFAULT 0 NOT NULL ,
    TRABAJADORES_ID NUMBER (7) NOT NULL ,
    FECHA_ID        DATE
  ) ;
ALTER TABLE VIAJES ADD CONSTRAINT VJS_HF_CHK CHECK (HORAFINAL    > HORAINICIAL) ;
ALTER TABLE VIAJES ADD CONSTRAINT VJS_HI_CHK CHECK (HORAINICIAL >= 0) ;
ALTER TABLE VIAJES ADD CONSTRAINT VIAJES_PK PRIMARY KEY ( horaInicial ) ;


ALTER TABLE AVISOS ADD CONSTRAINT AVISOS_PARTES_FK FOREIGN KEY (
TRABAJADORES_ID, FECHA_ID ) REFERENCES PARTES ( TRABAJADORES_ID, fecha );

ALTER TABLE PARTES ADD CONSTRAINT PARTES_TRABAJADORES_FK FOREIGN KEY (
TRABAJADORES_ID ) REFERENCES TRABAJADORES ( ID );

ALTER TABLE TRABAJADORES ADD CONSTRAINT TRABAJADORES_CENTROS_FK FOREIGN KEY (
CENTROS_ID ) REFERENCES CENTROS ( ID ) NOT DEFERRABLE ;

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_TRABAJADORES_FK FOREIGN KEY (
TRABAJADORES_ID ) REFERENCES TRABAJADORES ( ID ) ON
DELETE;

ALTER TABLE VEHICULOS ADD CONSTRAINT VHC_TRF_FK FOREIGN KEY ( fecha )
REFERENCES PARTES ( TRABAJADORES_ID, fecha );

ALTER TABLE VIAJES ADD CONSTRAINT VIAJES_PARTES_FK FOREIGN KEY (
TRABAJADORES_ID, FECHA_ID ) REFERENCES PARTES ( TRABAJADORES_ID, fecha );