INSERT INTO CENTROS VALUES (1,'EJGV','PEPITO',3,'VITORIA',01002,'ALAVA',687035444);
     
create or replace procedure AltaTrabajador
(PID TRABAJADORES.ID%TYPE,
PDNI TRABAJADORES.DNI%TYPE,
PNOMBRE TRABAJADORES.NOMBRE%TYPE,
PPRIMER TRABAJADORES.PRIMERAPELLIDO%TYPE,
PSEGUNDO TRABAJADORES.SEGUNDOAPELLIDO%TYPE,
PCATEGORIA TRABAJADORES.CATEGORIA%TYPE,
PCALLE TRABAJADORES.CALLE%TYPE,
PNUMERO TRABAJADORES.NUMERO%TYPE,
PCIUDAD TRABAJADORES.CIUDAD%TYPE,
PCP TRABAJADORES.CODIGOPOSTAL%TYPE,
PMOVILEM TRABAJADORES.MOVILEMPRESA%TYPE,
PIDCENTRO TRABAJADORES.CENTROS_ID_CENT%TYPE
)
as
BEGIN

INSERT INTO TRABAJADORES (ID,DNI,NOMBRE,PRIMERAPELLIDO,SEGUNDOAPELLIDO,CATEGORIA,CALLE,NUMERO,CIUDAD,CODIGOPOSTAL,MOVILEMPRESA,CENTROS_ID_CENT)
VALUES(PID,PDNI,PNOMBRE,PPRIMER,PSEGUNDO,PCATEGORIA,PCALLE,PNUMERO,PCIUDAD,PCP,PMOVILEM,PIDCENTRO);
INSERT INTO USUARIOS VALUES(PNOMBRE,PCATEGORIA,PID);
DBMS_OUTPUT.PUT_LINE('SE HAN MODIFICADO '||SQL%ROWCOUNT|| ' FILAS');

END AltaTrabajador;



EXECUTE ALTATRABAJADOR(1,'x3867920x','bruno','castro','freitas','informatica','reyes de navarra',33,'vitoria-gasteiz',010013,687035444,1);