--LOGIN
CREATE OR REPLACE PROCEDURE LOGIN
(USER IN USUARIOS.USUARIO%TYPE, PASS IN USUARIOS.PASSWORD%TYPE, CAT OUT TRABAJADORES.CATEGORIA%TYPE)
AS
P USUARIOS.PASSWORD%TYPE;
D TRABAJADORES.DNI%TYPE;
CLAVE_NO_VALIDA EXCEPTION;

BEGIN

SELECT PASSWORD INTO P
FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS;

SELECT DNI INTO D
FROM TRABAJADORES WHERE ID=(SELECT TRABAJADORES_ID FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS);

IF (P=D) THEN 
RAISE CLAVE_NO_VALIDA;
ELSE 
SELECT CATEGORIA INTO CAT
FROM TRABAJADORES
WHERE ID=(SELECT TRABAJADORES_ID FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS);
      
END IF;

EXCEPTION 
WHEN CLAVE_NO_VALIDA THEN 
    RAISE_APPLICATION_ERROR(-20001,'ACTUALIZA TU CONTRASEÑA.');
WHEN NO_DATA_FOUND THEN
   RAISE_APPLICATION_ERROR(-20002,'NO SE ENCUENTRAN REGISTROS.'); 
END LOGIN;

--PAQUETE LOGIN
CREATE OR REPLACE PACKAGE PLOGIN
AS
PROCEDURE VALIDACION (USER IN USUARIOS.USUARIO%TYPE, PASS IN USUARIOS.PASSWORD%TYPE, CAT OUT TRABAJADORES.CATEGORIA%TYPE);
PROCEDURE ACTUALIZAR (USER IN USUARIOS.USUARIO%TYPE, PASS IN USUARIOS.PASSWORD%TYPE, PASS2 IN USUARIOS.PASSWORD%TYPE, PASS3 IN USUARIOS.PASSWORD%TYPE);
END PLOGIN;

CREATE OR REPLACE PACKAGE BODY PLOGIN
AS 
PROCEDURE VALIDACION (USER IN USUARIOS.USUARIO%TYPE, PASS IN USUARIOS.PASSWORD%TYPE, CAT OUT TRABAJADORES.CATEGORIA%TYPE)
AS
P USUARIOS.PASSWORD%TYPE;
D TRABAJADORES.DNI%TYPE;
CLAVE_NO_VALIDA EXCEPTION;
BEGIN

SELECT PASSWORD INTO P
FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS;

SELECT DNI INTO D
FROM TRABAJADORES WHERE ID=(SELECT TRABAJADORES_ID FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS);

IF (P=D) THEN 
RAISE CLAVE_NO_VALIDA;
ELSE 
SELECT CATEGORIA INTO CAT
FROM TRABAJADORES
WHERE ID=(SELECT TRABAJADORES_ID FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS);
      
END IF;

EXCEPTION 
WHEN CLAVE_NO_VALIDA THEN 
    RAISE_APPLICATION_ERROR(-20001,'ACTUALIZA TU CONTRASEÑA.');
WHEN NO_DATA_FOUND THEN
   RAISE_APPLICATION_ERROR(-20002,'NO SE ENCUENTRAN REGISTROS.'); 
END VALIDACION;

PROCEDURE ACTUALIZAR (USER IN USUARIOS.USUARIO%TYPE, PASS IN USUARIOS.PASSWORD%TYPE, PASS2 IN USUARIOS.PASSWORD%TYPE, PASS3 IN USUARIOS.PASSWORD%TYPE)
AS
P USUARIOS.PASSWORD%TYPE;
D TRABAJADORES.DNI%TYPE;
CLAVE_NO_VALIDA EXCEPTION;
NUEVA_CLAVE_NO_COINCIDE EXCEPTION;

BEGIN 
SELECT PASSWORD INTO P
FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS;

SELECT DNI INTO D
FROM TRABAJADORES WHERE ID=(SELECT TRABAJADORES_ID FROM USUARIOS WHERE USUARIO=USER AND PASSWORD=PASS);

IF (P=D) THEN 
RAISE CLAVE_NO_VALIDA;
END IF;
IF (PASS2!=PASS3) THEN
RAISE NUEVA_CLAVE_NO_COINCIDE;
END IF;
IF (PASS2=PASS3) THEN
UPDATE USUARIOS
SET PASSWORD=PASS2
WHERE USUARIO=USER;
END IF;

EXCEPTION
WHEN CLAVE_NO_VALIDA THEN
RAISE_APPLICATION_ERROR(-20001,'ACTUALIZA TU CONTRASEÑA.');
WHEN NUEVA_CLAVE_NO_COINCIDE THEN
RAISE_APPLICATION_ERROR(-20003,'NUEVA CLAVE NO COINCIDE.');
END ACTUALIZAR; 
END PLOGIN;


--VISUALIZACION DE TODOS LOS CENTROS PAQUETES
CREATE OR REPLACE PACKAGE CONSULTACENTROS
AS 
PROCEDURE CENTROS (C OUT SYS_REFCURSOR);
END CONSULTACENTROS;

CREATE OR REPLACE PACKAGE BODY CONSULTACENTROS AS 
 PROCEDURE CENTROS(C OUT SYS_REFCURSOR) AS
 BEGIN 
  OPEN C FOR
SELECT ID, NOMBRE,  CALLE, NUMERO, CIUDAD, CODIGOPOSTAL, PROVINCIA, TELEFONO FROM CENTROS;
 END CENTROS;
END CONSULTACENTROS;


--VISUALIZACION DE TODOS LOS CENTROS Y DE UN CENTRO EN CONCRETO
DROP PACKAGE COMPLEJOS;

CREATE OR REPLACE PACKAGE COMPLEJOS
AS 
PROCEDURE CONSULTACENTROS (C OUT SYS_REFCURSOR);
PROCEDURE CONSULTACENTRO (C OUT SYS_REFCURSOR, BUSCAR IN VARCHAR2);
END COMPLEJOS;

CREATE OR REPLACE PACKAGE BODY COMPLEJOS AS 
 PROCEDURE CONSULTACENTROS(C OUT SYS_REFCURSOR) 
 AS
 BEGIN 
  OPEN C FOR
SELECT ID, NOMBRE,  CALLE, NUMERO, CIUDAD, CODIGOPOSTAL, PROVINCIA, TELEFONO FROM CENTROS;
   CLOSE C;
  END CONSULTACENTROS;

  PROCEDURE CONSULTACENTRO (C OUT SYS_REFCURSOR, BUSCAR IN VARCHAR2)
AS
 BEGIN 
OPEN C FOR
SELECT ID, NOMBRE,  CALLE, NUMERO, CIUDAD, CODIGOPOSTAL, PROVINCIA, TELEFONO FROM CENTROS;
CLOSE C;
END CONSULTACENTRO;
END COMPLEJOS;

--LISTADO DE EMPLEADOS
DROP PROCEDURE LISTADOEMPLEADOS;	
	
CREATE OR REPLACE PROCEDURE LISTADOEMPLEADOS
(IDN IN VARCHAR2, C OUT SYS_REFCURSOR)
AS
BEGIN
OPEN C FOR
SELECT * FROM TRABAJADORES WHERE CENTROS_ID=IDN;
CLOSE C;
END LISTADOEMPLEADOS;

--VER UN EMPLEADO
DROP PROCEDURE EMPLEADO;

CREATE OR REPLACE PROCEDURE EMPLEADO
(IDN IN VARCHAR 2, C OUT SYS_REFCURSOR)
AS 
BEGIN
OPEN C FOR
SELECT * FROM TRABAJADORES WHERE ID=IDN;
CLOSE C;
END EMPLEADO;